### ISSUE TITLE
Does is work with latest node?

### ISSUE THREAD

**Issue by etiennea** [stephank/node-libalac#2]
I get verbose stack Error: libalac@0.1.0 install: `node-gyp rebuild`

Does not work past 0.10.x because of 

```
 ../binding.cc:130:8: error: no member named 'Wrap' in 'alac::Encoder'
e->Wrap(args.This());
```

**Comment by kylewelsby** [comment]
This line, https://github.com/stephank/node-libalac/blob/master/binding.cc#L130

**Comment by microadam** [comment]
99% of the work is here: https://github.com/stephank/node-libalac/pull/3

**Comment by stephank** [comment]
I released 0.1.1, and the module should now build and run on a wide range of node versions. (Though, I think the implementation is a bit broken.)

**Comment by kylewelsby** [comment]
I can confirm this works on node `v4.1.1` very well thanks @microadam for the great work and @stephank for accepting the pull request.
